[[mounts]]
  source = "node_modules/@hyas/bootstrap/assets"
  target = "assets"

[[mounts]]
  source = "node_modules/@hyas/bootstrap/layouts"
  target = "layouts"

[[mounts]]
  source = "assets"
  target = "assets"

[[mounts]]
  source = "layouts"
  target = "layouts"
